#include "deep_arith_nesting.h"

/// 1200 additions: deeper than clang's 1024-bracket limit.
uint64_t DeepArithNesting::bump(uint64_t x) {
  return [&]() {
    auto _lit0 =
        (((((((((((((((((((((((((((((((x + UINT64_C(1)) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit1 = ((((((((((((((((((((((((((((((std::move(_lit0) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit2 = ((((((((((((((((((((((((((((((std::move(_lit1) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit3 = ((((((((((((((((((((((((((((((std::move(_lit2) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit4 = ((((((((((((((((((((((((((((((std::move(_lit3) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit5 = ((((((((((((((((((((((((((((((std::move(_lit4) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit6 = ((((((((((((((((((((((((((((((std::move(_lit5) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit7 = ((((((((((((((((((((((((((((((std::move(_lit6) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit8 = ((((((((((((((((((((((((((((((std::move(_lit7) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit9 = ((((((((((((((((((((((((((((((std::move(_lit8) + UINT64_C(1)) +
                                              UINT64_C(1)) +
                                             UINT64_C(1)) +
                                            UINT64_C(1)) +
                                           UINT64_C(1)) +
                                          UINT64_C(1)) +
                                         UINT64_C(1)) +
                                        UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1));
    auto _lit10 =
        ((((((((((((((((((((((((((((((std::move(_lit9) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit11 =
        ((((((((((((((((((((((((((((((std::move(_lit10) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit12 =
        ((((((((((((((((((((((((((((((std::move(_lit11) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit13 =
        ((((((((((((((((((((((((((((((std::move(_lit12) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit14 =
        ((((((((((((((((((((((((((((((std::move(_lit13) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit15 =
        ((((((((((((((((((((((((((((((std::move(_lit14) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit16 =
        ((((((((((((((((((((((((((((((std::move(_lit15) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit17 =
        ((((((((((((((((((((((((((((((std::move(_lit16) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit18 =
        ((((((((((((((((((((((((((((((std::move(_lit17) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit19 =
        ((((((((((((((((((((((((((((((std::move(_lit18) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit20 =
        ((((((((((((((((((((((((((((((std::move(_lit19) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit21 =
        ((((((((((((((((((((((((((((((std::move(_lit20) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit22 =
        ((((((((((((((((((((((((((((((std::move(_lit21) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit23 =
        ((((((((((((((((((((((((((((((std::move(_lit22) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit24 =
        ((((((((((((((((((((((((((((((std::move(_lit23) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit25 =
        ((((((((((((((((((((((((((((((std::move(_lit24) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit26 =
        ((((((((((((((((((((((((((((((std::move(_lit25) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit27 =
        ((((((((((((((((((((((((((((((std::move(_lit26) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit28 =
        ((((((((((((((((((((((((((((((std::move(_lit27) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit29 =
        ((((((((((((((((((((((((((((((std::move(_lit28) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit30 =
        ((((((((((((((((((((((((((((((std::move(_lit29) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit31 =
        ((((((((((((((((((((((((((((((std::move(_lit30) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit32 =
        ((((((((((((((((((((((((((((((std::move(_lit31) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit33 =
        ((((((((((((((((((((((((((((((std::move(_lit32) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit34 =
        ((((((((((((((((((((((((((((((std::move(_lit33) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit35 =
        ((((((((((((((((((((((((((((((std::move(_lit34) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit36 =
        ((((((((((((((((((((((((((((((std::move(_lit35) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit37 =
        ((((((((((((((((((((((((((((((std::move(_lit36) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    auto _lit38 =
        ((((((((((((((((((((((((((((((std::move(_lit37) + UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1)) +
           UINT64_C(1)) +
          UINT64_C(1)) +
         UINT64_C(1));
    return (((((((((((((((((((((((((((((std::move(_lit38) + UINT64_C(1)) +
                                       UINT64_C(1)) +
                                      UINT64_C(1)) +
                                     UINT64_C(1)) +
                                    UINT64_C(1)) +
                                   UINT64_C(1)) +
                                  UINT64_C(1)) +
                                 UINT64_C(1)) +
                                UINT64_C(1)) +
                               UINT64_C(1)) +
                              UINT64_C(1)) +
                             UINT64_C(1)) +
                            UINT64_C(1)) +
                           UINT64_C(1)) +
                          UINT64_C(1)) +
                         UINT64_C(1)) +
                        UINT64_C(1)) +
                       UINT64_C(1)) +
                      UINT64_C(1)) +
                     UINT64_C(1)) +
                    UINT64_C(1)) +
                   UINT64_C(1)) +
                  UINT64_C(1)) +
                 UINT64_C(1)) +
                UINT64_C(1)) +
               UINT64_C(1)) +
              UINT64_C(1)) +
             UINT64_C(1)) +
            UINT64_C(1));
  }();
}
