(include_subdirs qualified)

(env (_ (env-vars (INSIDE_DUNE "1") (CRANE_CHECK_IR "1"))))

(coq.theory
 (name CraneTestsWIP)
 (synopsis "Tests for the rocq-crane plugin")
 (modules :standard) ; automatically includes all .v files in this directory
 (theories
   Stdlib
   Crane
   ITree Equations ExtLib Paco)
 (flags (:standard -output-directory ../../tests/wip)))

(subdir z_abs_min
 (rule
  (targets z_abs_min.t.exe)
  (deps ZAbsMin.vo z_abs_min.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} z_abs_min.t.exe z_abs_min.cpp z_abs_min.t.cpp)))
 (rule
  (alias runtest)
  (deps z_abs_min.t.exe)
  (action (run ./z_abs_min.t.exe))))

(subdir z_arith_overflow
 (rule
  (targets z_arith_overflow.t.exe)
  (deps ZArithOverflow.vo z_arith_overflow.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} z_arith_overflow.t.exe z_arith_overflow.cpp z_arith_overflow.t.cpp)))
 (rule
  (alias runtest)
  (deps z_arith_overflow.t.exe)
  (action (run ./z_arith_overflow.t.exe))))

(subdir z_div_min
 (rule
  (targets z_div_min.t.exe)
  (deps ZDivMin.vo z_div_min.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} z_div_min.t.exe z_div_min.cpp z_div_min.t.cpp)))
 (rule
  (alias runtest)
  (deps z_div_min.t.exe)
  (action (run ./z_div_min.t.exe))))

(subdir rocq_bug_3287
 (rule
  (targets rocq_bug_3287.t.exe)
  (deps RocqBug3287.vo rocq_bug_3287.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} rocq_bug_3287.t.exe rocq_bug_3287.cpp rocq_bug_3287.t.cpp)))
 (rule
  (alias runtest)
  (deps rocq_bug_3287.t.exe)
  (action (run ./rocq_bug_3287.t.exe))))

(subdir fibst_cofix_repro
 (rule
  (targets fibst_cofix_repro.t.exe)
  (deps FibstCofixRepro.vo fibst_cofix_repro.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} fibst_cofix_repro.t.exe fibst_cofix_repro.cpp fibst_cofix_repro.t.cpp)))
 (rule
  (alias runtest)
  (deps fibst_cofix_repro.t.exe)
  (action (run ./fibst_cofix_repro.t.exe))))

(subdir loopify_gap_nested_fix
 (rule
  (targets loopify_gap_nested_fix.t.exe)
  (deps LoopifyGapNestedFix.vo loopify_gap_nested_fix.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} loopify_gap_nested_fix.t.exe loopify_gap_nested_fix.cpp loopify_gap_nested_fix.t.cpp)))
 (rule
  (alias runtest)
  (deps loopify_gap_nested_fix.t.exe)
  (action (run ./loopify_gap_nested_fix.t.exe))))

(subdir loopify_gap_ackermann
 (rule
  (targets loopify_gap_ackermann.t.exe)
  (deps LoopifyGapAckermann.vo loopify_gap_ackermann.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} loopify_gap_ackermann.t.exe loopify_gap_ackermann.cpp loopify_gap_ackermann.t.cpp)))
 (rule
  (alias runtest)
  (deps loopify_gap_ackermann.t.exe)
  (action (run ./loopify_gap_ackermann.t.exe))))

(subdir mutual_tmc_loopify
 (rule
  (targets mutual_tmc_loopify.t.exe)
  (deps MutualTmcLoopify.vo mutual_tmc_loopify.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} mutual_tmc_loopify.t.exe mutual_tmc_loopify.cpp mutual_tmc_loopify.t.cpp)))
 (rule
  (alias runtest)
  (deps mutual_tmc_loopify.t.exe)
  (action (run ./mutual_tmc_loopify.t.exe))))

(subdir cps_continuation_copy
 (rule
  (targets cps_continuation_copy.t.exe)
  (deps CpsContinuationCopy.vo cps_continuation_copy.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} cps_continuation_copy.t.exe cps_continuation_copy.cpp cps_continuation_copy.t.cpp)))
 (rule
  (alias runtest)
  (deps cps_continuation_copy.t.exe)
  (action (run ./cps_continuation_copy.t.exe))))

(subdir concept_before_struct
 (rule
  (targets concept_before_struct.t.exe)
  (deps ConceptBeforeStruct.vo concept_before_struct.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} concept_before_struct.t.exe concept_before_struct.cpp concept_before_struct.t.cpp)))
 (rule
  (alias runtest)
  (deps concept_before_struct.t.exe)
  (action (run ./concept_before_struct.t.exe))))

(subdir curried_tvar_instantiation
 (rule
  (targets curried_tvar_instantiation.t.exe)
  (deps CurriedTvarInstantiation.vo curried_tvar_instantiation.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} curried_tvar_instantiation.t.exe curried_tvar_instantiation.cpp curried_tvar_instantiation.t.cpp)))
 (rule
  (alias runtest)
  (deps curried_tvar_instantiation.t.exe)
  (action (run ./curried_tvar_instantiation.t.exe))))

(subdir enum_after_use
 (rule
  (targets enum_after_use.t.exe)
  (deps EnumAfterUse.vo enum_after_use.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} enum_after_use.t.exe enum_after_use.cpp enum_after_use.t.cpp)))
 (rule
  (alias runtest)
  (deps enum_after_use.t.exe)
  (action (run ./enum_after_use.t.exe))))

(subdir erased_index_fun_type
 (rule
  (targets erased_index_fun_type.t.exe)
  (deps ErasedIndexFunType.vo erased_index_fun_type.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} erased_index_fun_type.t.exe erased_index_fun_type.cpp erased_index_fun_type.t.cpp)))
 (rule
  (alias runtest)
  (deps erased_index_fun_type.t.exe)
  (action (run ./erased_index_fun_type.t.exe))))

(subdir erased_method_receiver
 (rule
  (targets erased_method_receiver.t.exe)
  (deps ErasedMethodReceiver.vo erased_method_receiver.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} erased_method_receiver.t.exe erased_method_receiver.cpp erased_method_receiver.t.cpp)))
 (rule
  (alias runtest)
  (deps erased_method_receiver.t.exe)
  (action (run ./erased_method_receiver.t.exe))))

(subdir higher_rank_poly
 (rule
  (targets higher_rank_poly.t.exe)
  (deps HigherRankPoly.vo higher_rank_poly.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} higher_rank_poly.t.exe higher_rank_poly.cpp higher_rank_poly.t.cpp)))
 (rule
  (alias runtest)
  (deps higher_rank_poly.t.exe)
  (action (run ./higher_rank_poly.t.exe))))

(subdir hkt_instance_arg_order
 (rule
  (targets hkt_instance_arg_order.t.exe)
  (deps HktInstanceArgOrder.vo hkt_instance_arg_order.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} hkt_instance_arg_order.t.exe hkt_instance_arg_order.cpp hkt_instance_arg_order.t.cpp)))
 (rule
  (alias runtest)
  (deps hkt_instance_arg_order.t.exe)
  (action (run ./hkt_instance_arg_order.t.exe))))

(subdir hkt_partial_app_instance
 (rule
  (targets hkt_partial_app_instance.t.exe)
  (deps HktPartialAppInstance.vo hkt_partial_app_instance.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} hkt_partial_app_instance.t.exe hkt_partial_app_instance.cpp hkt_partial_app_instance.t.cpp)))
 (rule
  (alias runtest)
  (deps hkt_partial_app_instance.t.exe)
  (action (run ./hkt_partial_app_instance.t.exe))))

(subdir hkt_record_dict
 (rule
  (targets hkt_record_dict.t.exe)
  (deps HktRecordDict.vo hkt_record_dict.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} hkt_record_dict.t.exe hkt_record_dict.cpp hkt_record_dict.t.cpp)))
 (rule
  (alias runtest)
  (deps hkt_record_dict.t.exe)
  (action (run ./hkt_record_dict.t.exe))))

(subdir instance_field_at_fun_type
 (rule
  (targets instance_field_at_fun_type.t.exe)
  (deps InstanceFieldAtFunType.vo instance_field_at_fun_type.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} instance_field_at_fun_type.t.exe instance_field_at_fun_type.cpp instance_field_at_fun_type.t.cpp)))
 (rule
  (alias runtest)
  (deps instance_field_at_fun_type.t.exe)
  (action (run ./instance_field_at_fun_type.t.exe))))

(subdir map_over_partial_app
 (rule
  (targets map_over_partial_app.t.exe)
  (deps MapOverPartialApp.vo map_over_partial_app.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} map_over_partial_app.t.exe map_over_partial_app.cpp map_over_partial_app.t.cpp)))
 (rule
  (alias runtest)
  (deps map_over_partial_app.t.exe)
  (action (run ./map_over_partial_app.t.exe))))

(subdir poly_fn_as_arg_tvar_leak
 (rule
  (targets poly_fn_as_arg_tvar_leak.t.exe)
  (deps PolyFnAsArgTvarLeak.vo poly_fn_as_arg_tvar_leak.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} poly_fn_as_arg_tvar_leak.t.exe poly_fn_as_arg_tvar_leak.cpp poly_fn_as_arg_tvar_leak.t.cpp)))
 (rule
  (alias runtest)
  (deps poly_fn_as_arg_tvar_leak.t.exe)
  (action (run ./poly_fn_as_arg_tvar_leak.t.exe))))

(subdir record_with_type_field
 (rule
  (targets record_with_type_field.t.exe)
  (deps RecordWithTypeField.vo record_with_type_field.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} record_with_type_field.t.exe record_with_type_field.cpp record_with_type_field.t.cpp)))
 (rule
  (alias runtest)
  (deps record_with_type_field.t.exe)
  (action (run ./record_with_type_field.t.exe))))
